### ISSUE TITLE
Cannot install eclipse plugin - unable to read repository

### ISSUE THREAD

**Issue by jeanpalaz** [knopflerfish/eclipse.knopflerfish.org#5]
Hello,

I have an issue installing Knopflerfish in eclipse LUNA SR2 (for another dependency have to use this eclipse version)
In Eclipse -> Help -> install new software -> Add repository
Name Knopflerfish ,location : https://www.knopflerfish.org/eclipse-update/

But I have this error message 
org.eclipse.equinox.p2.core.ProvisionException

Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.

Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.
hostname in certificate didn't match: <www.knopflerfish.org> != <*.oderland.com> OR <*.oderland.com> OR <oderland.com>

THX for helping
Jean

**Comment by jeanpalaz** [comment]
I tried to download https://www.knopflerfish.org/eclipse-update/features/org.knopflerfish.eclipse.ide_feature_1.2.3.jar
and add the jar but it doesn't work:
Could not find jar:file:/C:/temp/org.knopflerfish.eclipse.ide_feature_1.2.3.jar!/

Is there any compatibility with Luna?

thx

**Comment by jeanpalaz** [comment]
Hello,
So I have tested with Oxygen and 
 I have another probleme now with  Oxygen.1a Release (4.7.1a) 32 bits

Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.
Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

May be a repo problem?

Bye
Jean

**Comment by chlarsson** [comment]
I just tried it using Oxygen 4.7.0 and it worked.

We recently changed the whole site to use https instead of http. 

Can you browse to the repo?
https://www.knopflerfish.org/eclipse-update/site.xml

Which version of Java are you running Eclipse under?

The repository URL shouldn't contain the "content.xml" part, but maybe that's just the error message you are getting?

**Comment by jeanpalaz** [comment]
Hi
I'm using (using in eclipse.ini -vm C:\dev\bin\jdk1.8.0_111\jre\bin\javaw.exe)

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

I can browse  https://www.knopflerfish.org/eclipse-update/site.xml

<site><description name="Knopflerfish Update Site" url="http://www.knopflerfish.org/eclipse-update">
      Knopflerfish Eclipse Plugins Update Site
   </description><feature url="features/org.knopflerfish.eclipse.ide_feature_1.2.3.jar" id="org.knopflerfish.eclipse.ide_feature" version="1.2.3"><category name="Knopflerfish"/></feature><category-def name="Knopflerfish" label="Knopflerfish Plugin"><description>
         The Knopflerfish OSGi plugin
      </description></category-def></site>

**Comment by chlarsson** [comment]
Hi,
I suspect you have been hit by this issue:
https://www.eclipse.org/forums/index.php/t/1085851/

**Comment by chlarsson** [comment]
There is additional info here:
https://community.jaspersoft.com/wiki/solving-installation-and-update-errors-related-update-site-jaspersoft-studio

The article mentions Let's Encrypt certificates, which is exactly what the Knopflerfish site uses.

**Comment by chlarsson** [comment]
Hi again,
After further googling I found there is mor info here:
https://www.topjavablogs.com/news/how-to-trust-lets-encrypt-certificate-with-java

The articly suggest  you should use the JDK to run eclipse to. In your comment it seems like you are running the JRE, not the JDK?

**Comment by jeanpalaz** [comment]
OK let's try these solutions

- remove -Djavax.net.ssl.truststore (originaly I don't have)
- change local_policy.jar, US_export_policy.jar  in  ${JAVA_HOME}/jdk/jre/lib/security  (https://stackoverflow.com/questions/38203971/javax-net-ssl-sslhandshakeexception-received-fatal-alert-handshake-failure/38264878#38264878)
- "-vm C:\dev\bin\jdk1.8.0_111\bin\javaw.exe" restart eclipse

Both tried with Oxygen and Luna (32 bits)

Same error ... :(

**Comment by chlarsson** [comment]
I think you should add the local_policy.jar to the JDK?

**Comment by jeanpalaz** [comment]
There is no lib/security in jdk only in jdk/jre/lib/security, I follow the readme in downloaded patch in http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by chlarsson** [comment]
ah, ok. 

Strange that the suggested fixes didn't solve the problem.

We will test this ourselves by doing a fresh install of eclipse and java on a windows machine.

**Comment by jeanpalaz** [comment]
So I have done all my tests from scratch and then the bug was in eclipse.ini
which option -vm C:\dev\bin\jdk1.8.0_111\jre\bin\javaw.exe MUST BE on 2 SEAPRATE lines
-vm
C:\dev\bin\jdk1.8.0_111\jre\bin\javaw.exe 
(https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Windows_Example)
So the old  JRE by default was loaded. (turn me crazy since 2 days)

Finally Wiht JDK 1.8.0_111 32 or 64 bits with appropriate eclipse (32-64) is working with neon and oxygen, and without mentioned patch.

But I still have an issue the original mentioned at begining:
with Eclipse LUNA 32 bits and Jdk 1.8.0_111 32 bits, I have this issue

Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.
Unable to read repository at https://www.knopflerfish.org/eclipse-update/content.xml.
hostname in certificate didn't match: <www.knopflerfish.org> != <*.oderland.com> OR <*.oderland.com> OR <oderland.com>

Thanks a lot for support !

**Comment by chlarsson** [comment]
It's probably the same problem, but Luna is handing the https connection differently. 

This might do the trick:
https://groups.google.com/forum/#!topic/antlr4ide/6jOr-MZV0lk

As a fallback we can probably also pack the plugin as a zip/tar which can be downloaded and installed locally, as a workaround.

**Comment by jeanpalaz** [comment]
Yes the workaround would be great , andfor many people behind a very restrictive proxy too ...

The follinwg trick does not work

-vm
C:\dev\bin\jdk1.8.0_111\bin\javaw.exe
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Djsse.enableSNIExtension=false
-Xms40m
-Xmx512m

I think this the right location for this option

**Comment by chlarsson** [comment]
Ironically I'm at Eclipsecon / OSGi Community Event at the moment ;-) 

So please bare with us before we can get it packaged and uploaded as a zip/tar

**Comment by janste63** [comment]
Hi,

I had the same problem as you have with Luna on Mars. But after upgrading the java sdk to 8u151 from 8u60, everything works correctly.

**Comment by jeanpalaz** [comment]
@janste63 : thanks for your comment, I have a production constraint to only used Jdk 8u111 but may be I can use the 8u151 just for installing Knopflerfish and then back again to 8u151

**Comment by janste63** [comment]
That will probably work.

**Comment by jeanpalaz** [comment]
Yes I confirm that's work

THX all
